services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_docker_development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ..:/rails:cached
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/rails_docker_development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY:-}
      BOOTSNAP_CACHE_DIR: /tmp/bootsnap-cache
    stdin_open: true
    tty: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

volumes:
  postgres_data:
  bundle_cache:
  node_modules:
